name: carbnb
description: "A new Flutter CARBNB project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.10+11

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  melos: ^6.2.0
  get_it: ^8.0.2
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  intl: any
  dependency:
    path: packages/core/dependency
  navigation:
    path: packages/core/navigation
  intent_launcher:
    path: packages/core/intent_launcher
  data:
    path: packages/data
  domain:
    path: packages/domain
  common:
    path: packages/presentation/common
  splash:
    path: packages/presentation/splash
  authentication:
    path: packages/presentation/authentication
  main:
    path: packages/presentation/main
  home:
    path: packages/presentation/home
  locations:
    path: packages/presentation/locations
  favourites:
    path: packages/presentation/favourites
  profile:
    path: packages/presentation/profile

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
