name: locations
description: "A new Flutter package project."

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  flutter_svg: ^2.0.16
  common:
    path: ../common