name: main
description: "A new Flutter package project."

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  equatable: ^2.0.7
  flutter_svg: ^2.0.16
  cached_network_image: ^3.4.1
  skeletonizer: ^1.4.2
  flutter_rating_bar: ^4.0.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  image_picker: ^1.1.2
  domain:
    path: ../../domain
  common:
    path: ../common
  intent_launcher:
    path: ../../core/intent_launcher
  navigation:
    path: ../../core/navigation
  dependency:
    path: ../../core/dependency
  home:
    path: ../../presentation/home
  locations:
    path: ../../presentation/locations
  favourites:
    path: ../../presentation/favourites
  profile:
    path: ../../presentation/profile
