arb-dir: lib/l10n/translations
output-dir: lib/l10n/generated
template-arb-file: app_ru.arb
output-localization-file: app_localizations.dart
#output-class: L10N
nullable-getter: false
synthetic-package: false