name: common
description: "Common features"

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  equatable: ^2.0.7
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.16
  fluttertoast: ^8.2.10
  syncfusion_flutter_datepicker: ^27.2.4
  time_range: ^1.1.1
  intent_launcher:
    path: ../../core/intent_launcher

flutter:
  uses-material-design: true
  generate: true # Add this line
  assets:
    - assets/images/
    - assets/onboarding/
    - assets/menu/
    - assets/favourites/
    - assets/main/
    - assets/home/
    - assets/locations/
    - assets/profile/

  fonts:
    - family: BOLD
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
    - family: REGULAR
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
    - family: LIGHT
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Light.ttf
    - family: MEDIUM
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf