name: common
description: "Common features"

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  equatable: ^2.0.7
  flutter_svg: ^2.0.16

flutter:
  uses-material-design: true
  generate: true # Add this line
  assets:
    - assets/images/
    - assets/onboarding/
    - assets/menu/

  fonts:
    - family: BOLD
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
    - family: REGULAR
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
    - family: LIGHT
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Light.ttf
    - family: MEDIUM
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf