name: common
description: "Common features"

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  equatable: ^2.0.7

flutter:
  generate: true # Add this line
